version: '3'
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=flancoDB
      - POSTGRES_USER=flancoDB
      - POSTGRES_PASSWORD=flancoDB
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: